import ConfirmationContextProvider from "@/context/confirmationPopup";
import ConfirmationPopup from "@/components/molecule/popup";
import AlertProvider from "@/context/alertProvider";
import Notification from "@/components/molecule/notification";
import { Metadata } from "next";
import LogoutButton from "@/components/molecule/logoutButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfirmationContextProvider>
      <AlertProvider>
        <>
          {children}
          <ConfirmationPopup />
          <Notification />
          <LogoutButton />
        </>
      </AlertProvider>
    </ConfirmationContextProvider>
  );
}
